### PR TITLE
Update CKEditor to 4.4.8

### PR DESCRIPTION
**Pull request by ydwis40**

### CODE REVIEW

**Comment by ikoniqoz** [comment]
There are a few changes proposed that I believe should re-considered for compatability/consistency reasons with what has been the accepted standard for many years. One in particular is the proposal to change the shiftEnterMode parameter in config.js which should be left as config.shiftEnterMode = CKEDITOR.ENTER_BR which is an industry standard. What is proposed is that both Enter and ShiftEnter cause a new paragraph and there is no provision for entering a new line if both config.shiftEnterMode  and config.EnterMode both cause a new para.

Another point I could make while on the subject is to do with a matter that caused much consternation in the 2.x branch for quite a while, was the behaviour that was experienced when text was copied from one instance of the editor and pasted into another instance. We were plagued with spurious inline HTML for font and line spacing on the pasted content. I eventually resolved this by removing the font size and line height settings in the .cke_editable code block of the contents.css file. 

For what it is worth, in all my 2.2.5 sites I have  included the PastText plugin. I then replace the Paste button with the Past as Plain Text button in the Toolbar. The Paste from Word plugin is another can of worms in more than 10 years of using CKeditor in various projects....

Even so, it is probably as good a time as any to upgrade CKeditor, so thanks to ydwis40 for pushing on with this proposal.

**Comment by ydwis40** [comment]
I'm new using git. What you've described is indeed my fault.

Should I have to make a new pull request or not (to fix this)?

**Comment by ikoniqoz** [comment]
Congratulations for making the start. Its more than I am game to do and I have been mulling over the CKeditor edits I have made for some time, plus other needed fixes I have implemented recently to resolve Google Analytics issues. - these needed fixes I hope to attempt over the coming weekend, In the meantime, you could probably cancel your PR somehow - check with ryan@pyrocms.com. And welcome to the PyroCMS crowd!.

**Comment by RyanThompson** [comment]
This is pretty large and scary. Im going to stick to security patches for 2.x - sorry folks. You can use the fork or merge this yourself if needed :-/

**Pull request closed without merging**
