### PR TITLE
Change composer.json

### PR DESCRIPTION
**Pull request by fryiee**
- Rollback to class map (this is a breaking test change for no real gain)
- Add backported laravel-browserkit-testing (could add dusk but I think assuming that is not worth it)
- Add streams-platform addons to composer.json (we need this for testing)
- Remove the default tests as it implies that tests should go in that folder rather than in addons etc
- remove trait (used in dusk setup, not needed with browserkit)
- set TestCase to extend browserkit testcase rather than illuminate

This goes side by side with the changes in https://github.com/anomalylabs/users-module/pull/80

### CODE REVIEW

**Comment by mattdillon100** [comment]
This is great! When can we expect this to be merged in?

**Comment by RyanThompson** [comment]
This is fantastic! HOWEVER.. I want to stay as transparent / inline with Laravel as absolutely possible. Which means using the testing suite they suggest. "Backported" anything is usually kinda scary. Why would we not just use what Laravelers use?

**Comment by Piterden** [comment]
That's why we use Repositories instead of ActiveRecord?

**Comment by RyanThompson** [comment]
@Piterden please omit yourself from the conversation less you have something to add to it.

**Comment by fryiee** [comment]
Just realised that I commented on everything before reading the replies from notifications. *slaps forehead*

*retracted, looks like you can indeed hook up Dusk to PHPUnit*

Although, if we are going to go with Dusk, then the namespacing changes you made will be necessary as I believe Dusk has to use application-style autoloading to get at tests.

**Comment by fryiee** [comment]
It's also awfully slow for basic tests.

**Pull request merged**
