### PR TITLE
Exclude redirects module, cause it not works.

### PR DESCRIPTION
**Pull request by Piterden**

### CODE REVIEW

**Comment by huglester** [comment]
Anyway it is not probably needed in most project?
I personnaly do not have it installed in any of the projects.

@RyanThompson

**Comment by dakshhmehta** [comment]
+1

**Comment by Piterden** [comment]
I have it installed, but I also have to use nginx redirects, cause the module not redirects me where I want.

**Comment by Pixney-William** [comment]
So why do you exclude it instead of filing an issue @Piterden .. This being hidden as a pr means i didn't know about issues with it. Argh

**Comment by Pixney-William** [comment]
@RyanThompson Redirects doesnt work with posts for example.

**Comment by Piterden** [comment]
First exclude, then issue...

**Comment by keevitaja** [comment]
but perhaps redirects should not done in routing... rather before the URI hits the router?

I know it would be anti pattern, but at least it always works with simple a->b redirects.

**Comment by keevitaja** [comment]
@huglester at some point most projects will need it. like when you accidentally create a page with bad slug (in seo perspective) and you will change it when it has been out in the wild for some time.

**Comment by RyanThompson** [comment]
Our clients use this addon every single time - extensively. And turns out, it does work! So, no.

**Comment by Piterden** [comment]
```nginx
  location / {
    try_files $uri $uri/ /index.php?$query_string;

    location ~ (.+)/$ {
      if ($query_string) {
        return 301 https://$host$1?$query_string;
      }
      return 301 https://$host$1;
    }

    location ~ /en(.*)/?$ {
      return 301 https://$host/$1;
    }

    location ~* ^.+\.(jpeg|jpg|png|gif|bmp|ico|svg|css|js)$ {
      expires     max;
      add_header  Pragma public;
      add_header  Cache-Control "public, must-revalidate, proxy-revalidate";
    }

    location ~ [^/]\.php(/|$) {
      fastcgi_param     SCRIPT_FILENAME $document_root$fastcgi_script_name;

      fastcgi_pass      unix:/run/php/{awesome}.sock;
      fastcgi_index     index.php;
      include           /etc/nginx/fastcgi_params;
    }
    
    location ~ /articles/news/kto-preduprezhden,-tot-zashhishhen-osennie-privivki-ot-kleshhej/?$ {
      return 301 https://$host/articles/news/kto-preduprezhden-tot-zashhishhen-osennie-privivki-ot-kleshhej;
    }

    location ~ /articles/news/virus-grippa-narushaet-stenki-sosudov-–-napominayut-vrachi/?$ {
      return 301 https://$host/articles/news/virus-grippa-narushaet-stenki-sosudov-napominayut-vrachi;
    }

    location ~ /services/sanitarnye-knizhki-i-meditsinskie-spravki/(?!sanitarnaya-knizhka/)(.*)/?$ {
      return 301 https://$host/services/medspravki/$1;
    }

    location ~ /services/sanitarnye-knizhki-i-meditsinskie-spravki/sanitarnaya-knizhka/(.*)/?$ {
      return 301 https://$host/services/sanitarnaya-knizhka/$1;
    }

    location ~ /services/medspravki/sanitarnaya-knizhka/?$ {
      return 301 https://$host/services/sanitarnaya-knizhka;
    }

    location ~ /services/vaktsinatsiya-i-privivki/?(.*)?/?$ {
      return 301 https://$host/services/vakcinaciya/$1;
    }

    location ~ /services/vakcinaciya/vakcinaciya-varilriks/?$ {
      return 301 https://$host/services/vakcinaciya/varilriks;
    }

    location ~ /services/profosmotryi/(.*)/?$ {
      return 301 https://$host/services/drugie-uslugi/profosmotryi/$1;
    }

    location ~ /services/meditsinskie-analizy/(.*)/?$ {
      return 301 https://$host/services/analizy/$1;
    }

    location ~ /about/novosti/?$ {
      return 301 https://$host/articles/news?$args;
    }

    location ~ /about/novosti/?$ {
      return 301 https://$host/articles/news?$args;
    }
    
    location ~ /about/novosti/(.*)/?$ {
      return 301 https://$host/articles/news/$1;
    }
  }
```
This ^ works, but not the redirects-module. It is really useless. We must exclude it.

**Comment by huglester** [comment]
@Piterden where it does not work? with pages module?

**Comment by Piterden** [comment]
pages-module and also posts-module

**Comment by keevitaja** [comment]
i agree, that redirects does not work in posts-module. i had the same issue and fixed it with webserver redirect.

**Comment by RyanThompson** [comment]
You guys gotta realize some of this stuff isn't for you the developer. It's for users. We are not removing this addon because it _does_ serve it's purpose well to end users trying to setup redirects for their various needs and without server access.

**Comment by RyanThompson** [comment]
@Piterden if you like - submit a PR I would be happy to accept it. I understand it _should_ work for posts for example but it's a Laravel quirk as far as I can tell. There's an issue for it - it will be fixed. But removing it is not the solution.

I guess what I would like to see from you and others is maybe redirect your energy into something productive instead of argumentative. I think we can all agree it should do some things - as a community member you can help make that happen.

**Comment by designbywilliam** [comment]
Please guys.

1: We need to be able to discuss issues. 
2: Piterden, that line about being ashamed doesn't come off well at all. Please mind your phrasing.

**Comment by Piterden** [comment]
To tell everyone it works is not the solution, too.
I will try to do something when I would have a time.

**Pull request closed without merging**
