### PR TITLE
Update for Google Analytics Dashboard

### PR DESCRIPTION
**Pull request by marcogrueter**
new library (https://github.com/erebusnz/gapi-google-analytics-php-interface), Analytics.php stripped to what PyroCMS needs and migration update.

Todo list to enable the dashboard:

- create a project and enable google analytics api access in the google developer console
- create credentials
- download the .p12 key file and save it into system/cms/config/ga-key.p12
 set the service account e-mail in the backend settings, set ga profile id and the path to the ga-key.p12 file

would be great if a few people could test this PR and document the steps for the service account
this probably needs a more detailed explanation in the docs or something like that. accessing the google dev console can be a daunting task for "non-dev" users.

issues referenced in issue #3489, #3491

### CODE REVIEW

**Comment by RyanThompson** [comment]
Cool - I will give this a test in a bit. Nice work!

**Comment by mamarmite** [comment]
I'm diging in that right now, I can't make it work on localhost. did you success to activate that on localhost or on a prod server?

**Comment by mamarmite** [comment]
Ok, as always with that kind of "can't make it work", it was my patch applying method that didn't work. 
I installed a fresh 2.2 dev and merge that and it work yay! Thanks for that!

**Comment by huglester** [comment]
So this one makes the Google chart work on dashboard again?!

**Comment by RyanThompson** [comment]
Need someone to test it - I've been tied up with 3.0 launch / beta / docs

**Pull request merged**
